name: android4_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> "$GITHUB_OUTPUT"
      - name: Clone project
        run: git clone --depth=1 "${{ steps.get-project.outputs.PROJECT }}" project
      - name: Checkout Media 1.2.0
        uses: actions/checkout@v4
        with:
          repository: androidx/media
          ref:        1.2.0
          path:       media 
      - name: Patch media minSdk to 16
        run: |
          sed -i 's/minSdkVersion[[:space:]]*21/minSdkVersion 16/g' \
            media/libraries/datasource_okhttp/build.gradle
          echo "===== 修改后 build.gradle ====="
          cat media/libraries/datasource_okhttp/build.gradle
      - name: Create local.properties
        working-directory: ./project
        run: touch local.properties
        
      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: ./**/*.apk
          retention-days: 7

